name: ShallowSize
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: Detekt
        run: ./gradlew detekt
